"""Deterministic corpus for the context-pack contract fixture.

`context-pack.sample.json` (tests/fixtures/contracts/) is generated by running
the REAL builder — `pipeline.context_pack.build_context_pack` — over this
corpus. Both the generator (`scripts/gen_contract_fixtures.py`) and the
contract test (`tests/test_contract_fixtures.py`) import `build_reference_pack`
from here so the fixture and the schema assertion can never disagree about how
the pack is built.

This is NOT a `test_*` module, so pytest does not collect it; it is importable
as `tests.contract_corpus`.
"""

from __future__ import annotations

from pathlib import Path

from openaugi.model.block import Block
from openaugi.model.link import Link
from openaugi.pipeline.context_pack import build_context_pack
from openaugi.store.sqlite import SQLiteStore

# A fixed timestamp so the committed fixture is byte-stable across regenerations
# (the real builder stamps `datetime.now()`; the generator overwrites it with
# this). The value is irrelevant to the contract — only that the KEY exists.
SAMPLE_GENERATED_AT = "2026-07-08T00:00:00+00:00"


def _doc(title: str, path: str, block_time: str | None = None) -> Block:
    return Block(
        id=Block.make_document_id(path),
        kind="context_block:document",
        title=title,
        source="vault",
        block_time=block_time,
        metadata={"source_path": path},
    )


def _tag(name: str) -> Block:
    return Block(id=Block.make_tag_id(name), kind="context_block:tag", title=name, source="vault")


def _entry(content: str, path: str) -> Block:
    return Block(
        id=Block.make_id(path, Block.hash_content(content)),
        kind="data_block",
        content=content,
        source="vault",
        metadata={"source_path": path},
    )


def _populate(store: SQLiteStore) -> None:
    """Two containers with routing activity, a doc, an excluded task, tags."""
    amoc = _doc("AMOC - OpenAugi Main", "OpenAugi/AMOC - OpenAugi Main.md", "2026-07-01")
    pmoc = _doc("PMOC - Season 2", "OpenAugi/PMOC - Season 2.md", "2026-07-02")
    note = _doc("Local-first capture", "Notes/Local-first capture.md", "2026-07-05")
    task = _doc("TASK-2026-07-06-x", "OpenAugi/Tasks/TASK-2026-07-06-x.md", "2026-07-06")
    entry_a = _entry("thought a", "Daily/2026-07-05.md")
    entry_b = _entry("thought b", "Daily/2026-07-06.md")
    store.insert_blocks([amoc, pmoc, note, task, entry_a, entry_b, _tag("todo"), _tag("idea")])
    store.insert_links(
        [
            Link(from_id=entry_a.id, to_id=amoc.id, kind="routed_to"),
            Link(from_id=entry_a.id, to_id=Block.make_tag_id("todo"), kind="groups"),
            Link(from_id=entry_b.id, to_id=Block.make_tag_id("idea"), kind="groups"),
            Link(from_id=entry_b.id, to_id=pmoc.id, kind="routed_to"),
        ]
    )


def _write_vault_notes(vault: Path) -> None:
    """Curated vault notes the builder reads: taxonomy, conventions, lenses."""
    agent = vault / "OpenAugi" / "AGENT"
    (agent / "lenses").mkdir(parents=True, exist_ok=True)
    (agent / "My Taxonomy.md").write_text(
        "# My Taxonomy\n\nFacets: #area/openaugi #area/content #idea #question and #todo.\n"
    )
    (agent / "capture-conventions.md").write_text(
        "# Capture conventions\n\nOne idea per capture; tag with facet tags.\n"
    )
    (agent / "lenses" / "distill.md").write_text(
        "---\nname: distill\n"
        "description: Gather everything on a topic into ONE curated note with provenance.\n"
        "scope: recent writing\ntrigger: on-demand\ntarget: dashboard\n---\n\nIntent.\n"
    )


def build_reference_pack(workdir: Path) -> dict:
    """Build the context pack from the deterministic corpus.

    `workdir` doubles as the vault root and the DB location. Returns the pack
    dict exactly as `build_context_pack` produces it (including the live
    `generatedAt` — callers that want a stable fixture normalize it).
    """
    store = SQLiteStore(workdir / "corpus.db")
    try:
        _populate(store)
        _write_vault_notes(workdir)
        return build_context_pack(store, workdir)
    finally:
        store.close()
