"""Cross-repo contract fixtures — the openaugi half.

Three text/file contracts hold openaugi and private-augi-mobile together, and
today only lenient parsers and convention enforce them. The golden fixtures in
`tests/fixtures/contracts/` are the SHARED source of truth (mobile vendors
copies via `scripts/sync-contract-fixtures.sh`); this module pins openaugi's
side of each so a generator/parser change here can't silently drift from the
phone. See docs/plans/task-contract-fixtures.md and the "Contract fixtures"
section of the README.

The three contracts:

1. **context-pack.json shape** — `context-pack.sample.json` is generated by the
   REAL builder over `tests.contract_corpus`; here we assert a freshly built
   pack has the same keys/types (regenerate with `scripts/gen_contract_fixtures.py`
   if the contract legitimately changes).
2. **Nomination grammar** — the Dashboard nominations the review pass writes
   (`- [ ] **Verb:** … ^nom-<verb>-<slug>` + a nested `- answer:` slot) match
   the machine-readable grammar mobile's `reviewQueue.ts` parses.
3. **Capture anchors** — a mobile-written daily note ingests into the expected
   blocks/anchors.

We pin the floor (what MUST parse), never the ceiling: the parsers stay lenient
on purpose (Dashboards are LLM prose), so these tests never tighten them.
"""

from __future__ import annotations

import json
import re
import shutil
import tempfile
from pathlib import Path

from openaugi.adapters.vault import parse_vault
from tests.contract_corpus import build_reference_pack

CONTRACTS_DIR = Path(__file__).parent / "fixtures" / "contracts"
SAMPLE_PATH = CONTRACTS_DIR / "context-pack.sample.json"
DASHBOARD_PATH = CONTRACTS_DIR / "dashboard-nominations.md"
CAPTURE_PATH = CONTRACTS_DIR / "capture-daily-note.md"
REVIEW_TEMPLATE = (
    Path(__file__).parent.parent / "src" / "openaugi" / "templates" / "review-pass.md"
)


# ── Contract 1: context-pack.json shape ────────────────────────────


def _schema(value: object) -> object:
    """Recursive type skeleton: keys + value types, order-independent for lists.

    A non-empty list collapses to the set of its element schemas, so the fixture
    pins the *element* shape (e.g. `recentConcepts` items are `{title, path}`),
    not the number of elements.
    """
    if isinstance(value, dict):
        return {k: _schema(v) for k, v in sorted(value.items())}
    if isinstance(value, list):
        uniq: list = []
        for item in value:
            s = _schema(item)
            if s not in uniq:
                uniq.append(s)
        return ["list", *uniq]
    return type(value).__name__


def test_context_pack_sample_is_wellformed():
    """The committed sample is a complete, curated pack (so mobile's merge test
    exercises every field, not a degenerate empty one)."""
    sample = json.loads(SAMPLE_PATH.read_text())
    for key in ("agentFile", "taxonomy", "recentConcepts", "noteTitles", "lenses", "generatedAt"):
        assert key in sample, f"sample missing `{key}`"
    assert sample["taxonomy"] and sample["recentConcepts"] and sample["lenses"]
    assert all({"title", "path"} <= set(c) for c in sample["recentConcepts"])
    assert all({"name", "description"} <= set(lens) for lens in sample["lenses"])


def test_builder_output_matches_sample_schema():
    """A freshly built pack has the same keys/types as the committed sample.

    Breaks when `build_context_pack` gains/renames/retypes a field without
    regenerating the fixture — the exact drift the mobile consumer would hit.
    """
    sample = json.loads(SAMPLE_PATH.read_text())
    with tempfile.TemporaryDirectory() as tmp:
        fresh = build_reference_pack(Path(tmp))
    assert _schema(fresh) == _schema(sample)


# ── Contract 2: Dashboard nomination grammar ───────────────────────

# The machine-readable nomination: checkbox + bold verb + prose + a stable
# `^nom-<verb>-<slug>` anchor. Mirrors the shape `reviewQueue.ts` parses.
NOM_RE = re.compile(r"^- \[[ xX]\] \*\*[^*]+\*\* .+ \^nom-[a-z0-9-]+$")
# Any checkbox bullet that ends in a block anchor — the loose net used to FIND
# nominations, so a wrong anchor prefix is caught (not silently skipped).
CHECKBOX_ANCHORED_RE = re.compile(r"^- \[[ xX]\] .+ \^[\w-]+$")
ANSWER_SLOT_RE = re.compile(r"^\s+- answer:")


def _anchored_checkbox_lines(markdown: str) -> list[int]:
    lines = markdown.splitlines()
    return [i for i, line in enumerate(lines) if CHECKBOX_ANCHORED_RE.match(line)]


def test_dashboard_fixture_nominations_honor_grammar():
    md = DASHBOARD_PATH.read_text()
    lines = md.splitlines()
    idxs = _anchored_checkbox_lines(md)
    # The fixture ships exactly the four anchored nominations; the count guards
    # against a renamed anchor prefix vacuously passing the per-line check.
    assert len(idxs) == 4, f"expected 4 anchored nominations, found {len(idxs)}"
    for i in idxs:
        line = lines[i]
        assert NOM_RE.match(line), f"nomination violates grammar: {line!r}"
        assert i + 1 < len(lines) and ANSWER_SLOT_RE.match(lines[i + 1]), (
            f"nomination missing its `- answer:` slot: {line!r}"
        )


def test_review_pass_template_example_honors_grammar():
    """The nomination example the review-pass template teaches the agent to
    write must itself satisfy the grammar — template and parser stay in lockstep."""
    lines = [ln.strip() for ln in REVIEW_TEMPLATE.read_text().splitlines()]
    # Only the checkbox nomination bullet — not prose that merely mentions `^nom-`.
    nomination_lines = [ln for ln in lines if CHECKBOX_ANCHORED_RE.match(ln)]
    assert nomination_lines, "review-pass template has no `^nom-` nomination example"
    assert all(NOM_RE.match(ln) for ln in nomination_lines), nomination_lines
    assert any(ANSWER_SLOT_RE.match(f"    {ln}") for ln in lines if ln.startswith("- answer:"))


# ── Contract 3: capture daily-note anchors ─────────────────────────

ANCHOR_RE = re.compile(r"\^augi-[a-zA-Z0-9]{1,8}")


def test_capture_daily_note_ingests_to_expected_blocks():
    """A mobile-written daily note ingests as one block PER anchored entry.

    The splitter's anchor rule (2026-07-15): a line that is solely an Obsidian
    block anchor closes the segment above it, so each `… ^augi-<id8>` entry
    becomes its own content-hash block. The anchor stays in the raw hashed
    content but is extracted to metadata `anchor_id` and stripped from the
    stored content; the `HH:MM —` lead refines the block timestamp. Editing
    one entry re-ingests only that entry.
    """
    with tempfile.TemporaryDirectory() as tmp:
        vault = Path(tmp)
        cap = vault / "OpenAugi" / "Capture"
        cap.mkdir(parents=True)
        shutil.copy(CAPTURE_PATH, cap / "2026-07-08.md")

        blocks, links = parse_vault(vault)

    data = [b for b in blocks if b.kind == "data_block"]
    assert len(data) == 5
    assert all(b.metadata["granularity"] == "section" for b in data)

    assert [b.metadata.get("anchor_id") for b in data] == [
        "augi-a1b2c3d4",
        "augi-e5f6a7b8",
        "augi-c9d0e1f2",
        "augi-b3c4d5e6",
        "augi-d7e8f9a0",
    ]
    # Anchors are identity metadata, not content — stripped from every block.
    assert not any(ANCHOR_RE.search(b.content or "") for b in data)

    # The `HH:MM —` entry lead refines the `# 2026-07-08` header date into a
    # per-entry timestamp (including the bare-lead 16:45 grammar-first entry).
    assert [b.block_time for b in data] == [
        "2026-07-08T09:15:00",
        "2026-07-08T10:30:00",
        "2026-07-08T11:05:00",
        "2026-07-08T14:20:00",
        "2026-07-08T16:45:00",
    ]

    # Inline tags land on their own entry's block; the `zzz:` lens line is
    # extracted to a dispatch instruction on ITS entry (and stripped from
    # content); `aaa:` stays in the text. The 16:45 entry pins the
    # grammar-first shape: a block that OPENS with a zzz gets its timestamp
    # on its own line (mobile writer, 2026-07-15) so the token stays at line
    # start and dispatch fires.
    tagged = data[1]
    assert tagged.tags == ["idea", "area/openaugi"]
    assert "aaa: link this to OpenAugi Main" in (tagged.content or "")
    assert all(b.tags == [] for b in data if b is not tagged)

    assert data[3].metadata.get("zzz_instructions") == ["apply lens distill"]
    assert data[4].metadata.get("zzz_instructions") == ["recap my open questions from today"]
    assert all(b.metadata.get("zzz_instructions") is None for b in data[:3])
    assert not any("zzz:" in (b.content or "") for b in data)
