#!/usr/bin/env python3
"""session_cards.py — v0 session indexer: AI chat sessions -> vault session cards.

Scans local Claude Code (~/.claude/projects) and Codex (~/.codex/sessions)
transcript stores and materializes one small markdown "session card" per
session into the vault (default: OpenAugi/Sessions/), plus a newest-first
index note. Cards are regenerated on every run — link to them, don't edit
them. Delete the output folder to clean up completely.

Stdlib only. Usage:

    python3 scripts/session_cards.py --days 14          # vault from openaugi config
    python3 scripts/session_cards.py --vault ~/vault --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import time
from dataclasses import dataclass
from pathlib import Path

CARD_TAG = "#augi/session-card"
GENERATED_MARKER = "regenerated by scripts/session_cards.py — edits will be overwritten"


@dataclass
class Session:
    tool: str  # "claude" | "codex"
    session_id: str
    source_path: str
    project: str = ""
    git_branch: str = ""
    title: str = ""
    started: str = ""
    last_active: str = ""
    human_turns: int = 0
    agent_turns: int = 0
    first_human: str = ""
    last_human: str = ""

    @property
    def resume_command(self) -> str:
        if self.tool == "claude":
            proj = self.project or "."
            return f'cd "{proj}" && claude --resume {self.session_id}'
        return f"codex resume {self.session_id}"


def _text_of(content) -> str:
    """Extract plain text from a message content field (str or block list)."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict) and isinstance(block.get("text"), str):
                parts.append(block["text"])
        return "\n".join(parts)
    return ""


def _is_noise(text: str) -> bool:
    """Harness-injected user turns that aren't the human speaking."""
    t = text.lstrip()
    return (
        not t
        or t.startswith("<")  # <command-name>, <system-reminder>, <task-notification>
        or t.startswith("Caveat:")
    )


def parse_claude_session(path: Path) -> Session | None:
    s = Session(tool="claude", session_id=path.stem, source_path=str(path))
    timestamps: list[str] = []
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            for line in fh:
                try:
                    obj = json.loads(line)
                except (json.JSONDecodeError, ValueError):
                    continue
                if not isinstance(obj, dict):
                    continue
                if obj.get("type") == "ai-title" and obj.get("aiTitle"):
                    s.title = str(obj["aiTitle"])
                    continue
                ts = obj.get("timestamp")
                if isinstance(ts, str):
                    timestamps.append(ts)
                if obj.get("isSidechain"):
                    continue
                msg = obj.get("message")
                if not isinstance(msg, dict):
                    continue
                if obj.get("type") == "user" and msg.get("role") == "user":
                    origin = obj.get("origin")
                    if isinstance(origin, dict) and origin.get("kind") not in (None, "human"):
                        continue
                    text = _text_of(msg.get("content"))
                    if _is_noise(text):
                        continue
                    s.human_turns += 1
                    if not s.first_human:
                        s.first_human = text
                        s.project = obj.get("cwd", "") or s.project
                        s.git_branch = obj.get("gitBranch", "") or s.git_branch
                    s.last_human = text
                elif obj.get("type") == "assistant" and msg.get("role") == "assistant":
                    s.agent_turns += 1
    except OSError:
        return None
    if timestamps:
        s.started, s.last_active = min(timestamps), max(timestamps)
    return s if s.human_turns else None


def parse_codex_session(path: Path) -> Session | None:
    s = Session(tool="codex", session_id=path.stem, source_path=str(path))
    timestamps: list[str] = []
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            for line in fh:
                try:
                    obj = json.loads(line)
                except (json.JSONDecodeError, ValueError):
                    continue
                if not isinstance(obj, dict):
                    continue
                ts = obj.get("timestamp")
                if isinstance(ts, str):
                    timestamps.append(ts)
                payload = obj.get("payload")
                if not isinstance(payload, dict):
                    continue
                if obj.get("type") == "session_meta":
                    s.session_id = payload.get("session_id") or payload.get("id") or s.session_id
                    s.project = payload.get("cwd", "") or s.project
                    continue
                # User turns appear either as response_item messages or user_message events.
                text = ""
                if payload.get("type") == "message" and payload.get("role") == "user":
                    text = _text_of(payload.get("content"))
                elif payload.get("type") == "user_message":
                    text = _text_of(payload.get("message"))
                if text and not _is_noise(text):
                    s.human_turns += 1
                    if not s.first_human:
                        s.first_human = text
                    s.last_human = text
                elif payload.get("type") == "message" and payload.get("role") == "assistant":
                    s.agent_turns += 1
    except OSError:
        return None
    if timestamps:
        s.started, s.last_active = min(timestamps), max(timestamps)
    return s if s.human_turns else None


def _slug(text: str, max_len: int = 60) -> str:
    slug = re.sub(r"[^A-Za-z0-9 _-]+", "", text).strip().replace(" ", "-")
    return re.sub(r"-{2,}", "-", slug)[:max_len].strip("-") or "session"


def _trim(text: str, max_len: int = 600) -> str:
    text = text.strip()
    return text if len(text) <= max_len else text[: max_len - 1].rstrip() + "…"


def render_card(s: Session) -> str:
    title = s.title or _trim(s.first_human.splitlines()[0], 80)
    date = (s.started or "")[:10]
    front = "\n".join(
        [
            "---",
            "type: session-card",
            f"tool: {s.tool}",
            f"session_id: {s.session_id}",
            f'project: "{s.project}"',
            f'git_branch: "{s.git_branch}"',
            f"started: {s.started}",
            f"last_active: {s.last_active}",
            f"human_turns: {s.human_turns}",
            f"agent_turns: {s.agent_turns}",
            f'source_path: "{s.source_path}"',
            "---",
        ]
    )
    body = [
        front,
        "",
        f"# {date} · {title}",
        "",
        f"{CARD_TAG}",
        f"> {GENERATED_MARKER}",
        "",
        "## Intent (first human message)",
        "",
        _trim(s.first_human),
        "",
        "## Where it left off (last human message)",
        "",
        _trim(s.last_human),
        "",
        "## Resume",
        "",
        "```bash",
        s.resume_command,
        "```",
        "",
    ]
    return "\n".join(body)


def card_filename(s: Session) -> str:
    date = (s.started or "0000-00-00")[:10]
    title = s.title or s.first_human.splitlines()[0] if s.first_human else "session"
    return f"{date} - {s.tool} - {_slug(title)} - {s.session_id[:8]}.md"


def render_index(sessions: list[Session]) -> str:
    lines = [
        "---",
        "type: session-index",
        "description: Newest-first index of recent AI chat sessions. Regenerated; do not edit.",
        "---",
        "",
        "# Sessions — where I left off",
        "",
        f"{CARD_TAG}",
        f"> {GENERATED_MARKER}",
        "",
    ]
    for s in sorted(sessions, key=lambda x: x.last_active, reverse=True):
        name = card_filename(s)[:-3]
        title = s.title or _trim(s.first_human.splitlines()[0], 70)
        proj = Path(s.project).name if s.project else "?"
        lines.append(
            f"- {s.last_active[:16]} · **[[{name}]]** — {title} "
            f"(`{proj}`, {s.tool}, {s.human_turns}h/{s.agent_turns}a)"
        )
    lines.append("")
    return "\n".join(lines)


def collect(days: int, claude_dir: Path, codex_dir: Path) -> list[Session]:
    cutoff = time.time() - days * 86400
    sessions: list[Session] = []
    if claude_dir.is_dir():
        for f in claude_dir.glob("*/*.jsonl"):
            if f.stat().st_mtime < cutoff:
                continue
            parsed = parse_claude_session(f)
            if parsed:
                sessions.append(parsed)
    if codex_dir.is_dir():
        for f in codex_dir.rglob("rollout-*.jsonl"):
            if f.stat().st_mtime < cutoff:
                continue
            parsed = parse_codex_session(f)
            if parsed:
                sessions.append(parsed)
    return sessions


def resolve_vault(explicit: str | None) -> Path | None:
    """The vault root: the flag if given, else the openaugi config's default_path.

    The config lookup is optional so the script stays runnable as a plain
    file; without the package installed, --vault is simply required.
    """
    if explicit:
        return Path(explicit).expanduser()
    try:
        from openaugi.config import load_config, resolve_vault_path
    except ImportError:
        return None
    resolved = resolve_vault_path(None, load_config())
    return Path(resolved) if resolved else None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--vault",
        default=None,
        help="vault root (default: [vault] default_path from the openaugi config)",
    )
    ap.add_argument("--out", default="OpenAugi/Sessions", help="output folder, relative to vault")
    ap.add_argument("--days", type=int, default=14)
    ap.add_argument("--claude-dir", default="~/.claude/projects")
    ap.add_argument("--codex-dir", default="~/.codex/sessions")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    vault = resolve_vault(args.vault)
    if vault is None:
        ap.error("no vault: pass --vault or set [vault] default_path in the openaugi config")

    sessions = collect(
        args.days,
        Path(args.claude_dir).expanduser(),
        Path(args.codex_dir).expanduser(),
    )
    out_dir = vault / args.out
    if args.dry_run:
        for s in sorted(sessions, key=lambda x: x.last_active, reverse=True):
            print(f"{s.last_active[:16]}  {s.tool:6}  {s.human_turns:3}h  {card_filename(s)}")
        print(f"\n{len(sessions)} sessions -> {out_dir} (dry run, nothing written)")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for s in sessions:
        (out_dir / card_filename(s)).write_text(render_card(s), encoding="utf-8")
    (out_dir / "Sessions Index.md").write_text(render_index(sessions), encoding="utf-8")
    print(f"wrote {len(sessions)} cards + index -> {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
